# Generated by Django 5.0.6 on 2024-07-11 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postreport',
            old_name='reporting_user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='userreport',
            old_name='reporting_user',
            new_name='owner',
        ),
    ]
