# Generated by Django 5.0.6 on 2024-07-11 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_rename_reporting_user_postreport_owner_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postreport',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='userreport',
            options={'ordering': ['-created_at']},
        ),
    ]
